### ISSUE TITLE
Remove some unnessary default commands.

### ISSUE THREAD

**Issue by Okxa** [4d49/godot-console#1]
Nice project, but I think some of the default commands are unwanted, and currently require editing of plugin code to remove.

Default commands implemented should be only those that affect the console, so some of the commands should be removed to leave the decision to implement them to the game developer. **(Without having to edit plugin code)**

So currently only `help` and `clear` are commands that strictly affect the console, and candidates to be removed would be:

- `max_fps` & `physics_tics`: Should be removed 100%, it should be up to game developer if they allow those to be changed. These could be leaved as examples if commented out though.
- `quit` and `version`: Although these are commonly wanted anyways, leaving implementation to the game dev would be preferable.
- `test`: not needed in released projects using this console addon, but I understand if it is used for testing. Maybe a flag or something if you do not want it removed.

**Comment by 4d49** [comment]
Thank you. I agree that these commands should be removed.
