### ISSUE TITLE
Mono usage

### ISSUE THREAD

**Issue by lolomap** [4d49/godot-console#3]
How can I create command from C#? It seems like it does not support lambdas to pass arguments. If there is no solution now, can it be supported in future?

**Comment by 4d49** [comment]
@lolomap к сожалению я мало знаком с  C#.

> How can I create command from C#?
```cs
public void Multiply(float a, float b)
{
	GD.Print(a * b);
}

public override void _Ready()
{
	var console = GetNodeOrNull("/root/Console");
	if (!IsInstanceValid(console) || !console.HasMethod("create_command"))
	{
		return;
	}

	console.Call("create_command", "multiply", new Callable(this, MethodName.Multiply), "Command multiplies two numbers.");
}
```

> It seems like it does not support lambdas to pass arguments. If there is no solution now, can it be supported in future?

In the future I might rewrite to structures instead of classes, but it's unlikely to allow me to use lambdas from C#. To use lambdas from C#, I think you will need to write a special solution.

**Comment by lolomap** [comment]
А, понятно, я пытался использовать Callable.From() для передачи метода в качестве Callable и это работало только для функций без аргументов (с аргументами необходимо было оборачивать в лямбду). 
Тем не менее думаю было бы удобно иметь интерфейс для C# без необходимости в ручную получать ноду и использовать Call
