### ISSUE TITLE
"Assertion failed: Has command" while typing

### ISSUE THREAD

**Issue by nothke** [4d49/godot-console#7]
I'm getting a
```
Assertion failed: Has command.
```
while typing a command, it happens at random points along writing, sometimes it gets triggered while typing the second word.

Running in v4.2.1-rc1_mono

**Comment by nothke** [comment]
Sorry, the issue was actually my problem. I was restarting the level on "R" which triggered re-adding commands.

It would be nice to be able to use HasCommand() in C# as well tho.

**Comment by 4d49** [comment]
> It would be nice to be able to use HasCommand() in C# as well tho.

@nothke done!
